### PR TITLE
Add etcd checksums to support versions 3.3.19 and 3.4.6

### PR DESCRIPTION
**Pull request by tasdikrahman**
### Description

Add etcd checksums to support versions 3.3.19 and 3.4.6

Checksum for each version gotten from 
- https://github.com/etcd-io/etcd/releases/download/v3.3.19/SHA256SUMS
- https://github.com/etcd-io/etcd/releases/download/v3.4.6/SHA256SUMS

### Issues Resolved

https://github.com/chef-cookbooks/etcd/issues/96

### Check List

- [ ] All tests pass. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/TESTING.MD>
- [ ] New functionality includes testing.
- [x] New functionality has been documented in the README if applicable
- [ ] All commits have been signed for the Developer Certificate of Origin. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/CONTRIBUTING.MD>

### CODE REVIEW

**Comment by tasdikrahman** [comment]
@tas50 please review and let us know if something is missing.

**Comment by tasdikrahman** [comment]
Spec for `INSTANCE=service-systemd-opensuse-leap-15` https://travis-ci.org/github/chef-cookbooks/etcd/jobs/669164381?utm_medium=notification&utm_source=github_status, but checked that it's failing in master too https://travis-ci.org/github/chef-cookbooks/etcd/jobs/633026956?utm_medium=notification&utm_source=github_status. Let us know if that's a blocker.

**Comment by tasdikrahman** [comment]
Any updates on this please. Is the cookbook not maintained anymore? @tas50

**Comment by tas50** [comment]
Sorry for the delay @tasdikrahman. I rebased this and removed the version bump. Our tools handle that part automatically.

**Comment by tasdikrahman** [comment]
No worries, thanks for the merge.

**Pull request merged**
